### ISSUE TITLE
Please add Design System XD file here

### ISSUE THREAD

**Issue by jkornobis** [dxc-technology/halstack-style-guide#1]
Hello, 

I would like to know if it is possible to make the Adobe XD file available here?

Indeed the link on the site allows only to view the file in the preview mode of Adobe Cloud:
![image](https://user-images.githubusercontent.com/1469418/92396806-eff33980-f125-11ea-9a10-94a35f0c50cc.png)

Thank you in advance,
[Jérémie Kornobis](mailto:jkornobis2@dxc.com)
UX Designer - Design Next
Parisian team

**Comment by mawelCaballero** [comment]
Hello @jkornobis , 
Design system has been moved to this repository. Every time a pull request is merged to master branch it will be published.
