### ISSUE TITLE
[Tag] Component specs

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#100]
Icons users, color uses, padding should be fixed.
There are differences between components and documentation.

![Picture4](https://user-images.githubusercontent.com/75359999/115825668-629bf580-a427-11eb-98aa-afc5f80a17ab.png)

**Comment by aweell** [comment]
## Color

Halstack Purple color: #6f2c91
Implementation purple color is: #6b4187

## Padding

Source Design guidelines (table) : There's not padding specs
Source Design guidelines (image) 12px 30px 12px 30px
Source Implementation (React) 12px 30px 12px 30px 
Source Implementation (Angular) 30px(left) 30px(right) - Issue related to font family 

## Margin


Source Design guidelines (table) : 30px - 12px
Source Implementation (React) 12px 30px 12px 30px 

## Icon size

Source Design guidelines (table): 24x24px
Source Design guidelines (image): 24x24px
Source Implementation (React): 23x23px

# Font-family

Angular implementation is not using the proper font family.

**Comment by aweell** [comment]
Closed via #180
