### ISSUE TITLE
[Accordions] Angular components

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#101]
All types of accordians are not available.
Layout options are not there in components which is required for consistancy throught the applications.

![Picture5](https://user-images.githubusercontent.com/75359999/115825892-b0186280-a427-11eb-89ce-3e90d8b8e2dc.png)

**Comment by aweell** [comment]
Hello @GauravMaurya0,

We are discussing the possibility of adding more examples to the CDK sites. Since the accordion adapts itself to its parent and how the layout is built is not related to the component itself, we consider there's no design issue.
