### ISSUE TITLE
[Alert] Angular components

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#102]
Alert options with 'Yes, No' are not available in CDK comp

![Picture6](https://user-images.githubusercontent.com/75359999/115826505-a6dbc580-a428-11eb-9d04-bf8cc991ae5e.png)

**Comment by aweell** [comment]
Thanks @GauravMaurya0,

Custom content can be added to the alert component as children, so these buttons can be added in this way

Name | Default | Description
-- | -- | --
children: node |   | The details section of the alert. Can be used to render custom content in this area.

How buttons are displayed is covered in #113
