### ISSUE TITLE
[Chip] Angular components

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#103]
Edit, Delete, Info. chips aren't available in CDK

![Picture7](https://user-images.githubusercontent.com/75359999/115826637-da1e5480-a428-11eb-858b-2add5d407c9f.png)

**Comment by aweell** [comment]
Hello @GauravMaurya0,

We are discussing the possibility of adding more examples to the CDK sites. Since all chip variants are achievable with the CDKs, we consider there's no design issue.
