### ISSUE TITLE
[Dialog] Angular components

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#104]
Sizes are not similar, all options are not available in CDK whicg were mntioned in Design system

![Picture8](https://user-images.githubusercontent.com/75359999/115826805-15208800-a429-11eb-99c0-e107e61b8316.png)

**Comment by aweell** [comment]
Hello @GauravMaurya0, 

All dialog specs are covered in #49.

Please feel free to add any feedback there! :speech_balloon:
