### ISSUE TITLE
[Dropdown] Angular components

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#105]
Color options, other different options of dropdowns such as tree option isn't available

![Picture9](https://user-images.githubusercontent.com/75359999/115828187-fd4a0380-a42a-11eb-88c5-e44305cf31de.png)

**Comment by aweell** [comment]
Hello @GauravMaurya0,

We are discussing the possibility of adding more examples to the CDK sites. Since dropdown variants can be achieved by using the CDKs, we consider there's not any design issue.
