### ISSUE TITLE
[Heading] Angular componenents

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#106]
Sizes and padding aren't correect as per documentation
Alignments aren't same

![Picture10](https://user-images.githubusercontent.com/75359999/115828350-38e4cd80-a42b-11eb-9834-b1e2505d1a2f.png)

**Comment by aweell** [comment]
Hello @GauravMaurya0,

* The heading component has no padding.
* The alignment is not defined in the guidelines, so they can be `left`, `center` or `right` aligned.
* Sizes of angular implementation:

    | Level | px |
    | :--- | :----|
    | 1 | 60 |
    | 2 | 48 |
    | 3 | 32 |
    | 4 | 24 |
    | 5 | 20 |

It seems to be correct, please update showing an example of incorrect values.

**Comment by aweell** [comment]
Due to inactivity, I set the issue as closed.
