### ISSUE TITLE
[Link] Angular components

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#107]
Icons uses and states aren't well defined in the design system so CDK

![Picture11](https://user-images.githubusercontent.com/75359999/115828523-6e89b680-a42b-11eb-94b5-79399c07f7b1.png)

**Comment by aweell** [comment]
Hello @GauravMaurya0,

We are discussing the possibility of adding more examples to the CDK sites. Since any link variant can be done with CDKs, we consider there's not any design issue.
