### ISSUE TITLE
[Progress bar] Angular components

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#108]
All specifications, states, appearences aren't available in CDK
There should be all example available as per documentation for develeopment

![Picture12](https://user-images.githubusercontent.com/75359999/115828778-c7f1e580-a42b-11eb-97b0-f15e85d5607e.png)

**Comment by aweell** [comment]
Hello @GauravMaurya0,

We are discussing the possibility of adding more examples to the CDK sites. Since all progress-bar variants can be done with the CDK, we consider there's not any design issue.
