### ISSUE TITLE
[Result set table] Angular components

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#109]
Result set table components aren't available in design system 

![Picture13](https://user-images.githubusercontent.com/75359999/115828988-05567300-a42c-11eb-91da-6e80a88ca795.png)

**Comment by aweell** [comment]
Hello @GauravMaurya0,

We are discussing the possibility of adding more examples to the CDK sites. Until then since the table row can have any child, we consider there's not any design issue.
