### ISSUE TITLE
Feature Request for Text Editor Component.

### ISSUE THREAD

**Issue by goro0710** [dxc-technology/halstack-style-guide#11]
Designing a message center utility where we need to **compose** Emails. For that a WYSIWYG Text Editor is required. Below is an example.

![image](https://user-images.githubusercontent.com/11742574/100422456-5e55f100-30b0-11eb-9790-a03edfe7172d.png)

As an alternative we used ngx-quill library to implement this.
https://www.npmjs.com/package/ngx-quill

**Comment by peibolsang** [comment]
Please feel free to use this component. We are not considering to provide a value-added abstraction for this component in the short-term

**Comment by fsiddiqi** [comment]
+1 for QuillJS - it's licensed under the BSD license

Id like to propose  this as a compound/molecule component
