### ISSUE TITLE
[Table] Components specs

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#110]
Modes, states, paddings aren't properly available in CDK as this is mentioned in documentation.

![Picture14](https://user-images.githubusercontent.com/75359999/115829231-5c5c4800-a42c-11eb-9065-6341dfc22a53.png)

**Comment by GauravMaurya0** [comment]
## Padding Table header
Source Design guidelines (table) : 14px 20px 12px 40x
Source Design guidelines (image) : 14px 20px 12px 40x
Source Implementation (React) : 16px 20px 16px 40px
Source Implementation (Angular) : 40px 20px 14px 12x

## Padding Table body
Source Design guidelines (table) : 12px 20px 20px 20x
Source Design guidelines (image) : 14px 20px 12px 40x
Source Implementation (React) : 14px 20px 12px 40x
Source Implementation (Angular) : 14px 20px 12px 40x

## Font size Table header
Source Design guidelines (table) : 20px
Source Implementation (React) : 14px
Source Implementation (Angular) : 20px

## Font size Table body
Source Design guidelines (table) : 16px
Source Implementation (React) : 16px
Source Implementation (Angular) : 16px

## Divider
Source Design guidelines (table) : #D9D9D9
Source Implementation (React) : 
Source Implementation (Angular) : #bfbfbf

**Comment by aweell** [comment]
Thanks @GauravMaurya0,

It seems that the `padding` specs for top and bottom appear twice in the table. I'll add the divider and padding disparity comments in #57
