### ISSUE TITLE
Layout - Flexbox & grid

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-style-guide#125]
Is your feature request related to a problem? Please describe.
Missing Grid & FlexBox

Describe the solution you'd like
Have grid & flexbox
For example as https://getbootstrap.com/docs/4.0/layout/grid/
or https://material-ui.com/system/flexbox/#flexbox

**Comment by aweell** [comment]
Hi @NorbertPointu,

We plan to cover this feature in the near future. 

There is already an issue opened regarding the addition of grid layout (#48). Will be updated when moved to a new release milestone.

Please feel free to add any feedback there! :speech_balloon:
