### ISSUE TITLE
DxcAlert not responsive

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#13]
DxcAlert not responsive
In our case, the error returned from Cognito is big. we are not filtering the error message, we want to show complete text in the error box. The error text is visible on the screen till the end of the screen, rest all getting hidden.
We would like the text to get wrapped to next line to see complete error message as it could have information which user needs.

Can you please review and see if this is an issue or is this something which we can fix at our end itself?

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/72923647/100977603-33174a00-3567-11eb-9ef7-70120d0afc57.png)

**Comment by jsardid** [comment]
Closing it since we already allow children content on the alert.
