### ISSUE TITLE
CDK Limitation- Components cannot have multiple colors

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-style-guide#130]
Any component
In CDK theme color object it is not possible to define multiple color for the same component.
Color object: 
![image](https://user-images.githubusercontent.com/62135994/116510657-8ba80480-a8c5-11eb-89fd-f0a2204fb023.png)

Example use case:
Input date field needs to be in light/white color here as the background is dark
![image](https://user-images.githubusercontent.com/62135994/116510679-95316c80-a8c5-11eb-8029-1c1da168ac0e.png)
But normally on light background it should be dark.

Expected behavior
It should be possible to configure the color mode (light or dark) inside the components.

**Comment by aweell** [comment]
Hi @NorbertPointu,

We're already working on this feature (#116).  

Please feel free to add any feedback there! :speech_balloon:
