### ISSUE TITLE
[Footer] - Update documentation

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#138]
Design Specifications
---------------------

| Property | Value |
| --- | --- |
| Margin left/top/bottom | 20px |
| Margin right | 60px |
| Border Radius | 4px |
| Border thickness | 2px |
| Min. height short version | 120px |
| Min. height large version | 240px |
| Width | 100% |
| Font size (copyright, terms) | 12px |
| Font size (links) | 14px |
| Font size (section title) | 16px |
| Icon size | 20x20px |

Default footer example
----------------------

social icon size [**design spec]**: 20px x 20px
social icon size [**implementation**] : 25px x 25px
Links Font size [**design specs**] : 14px
Links Font size [**implementation**] : 12px

Footer with custom content
--------------------------
Links Font size [**design specs**]: 14px
Custom Links Font size [**implementation**]: 16px

Line above the the social icons is 100% in the tablet and mobile view and only to the width of the bottom links in the desktop view.

whereas in the images it is all the same in all views mobile/tablet/desktop only to the width of bottom links.

**Comment by aweell** [comment]
Closed via #274
