### ISSUE TITLE
[Header] - Update documentation

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#139]
Design Specifications
---------------------

| Property | Value |
| --- | --- |
| Padding right | 60px |
| Padding left | 36px |
| Padding top/bottom | 15px |
| Height | 64px |
| Min. width | 1024px |
| Distance between icons | 20px |
| Distance between icons and links | 40px |
| Distance between language and navigation | 150px |

padding left [**Design specs**] : 36px
padding left [**image**] : 20px

In '**Header with DxcHeaderDropdown**' example has following error

### `margin-bottom`

margin | value
-- | --
```xxsmall``` | 6px
```xsmall``` | 16px
```small``` | 24px
```medium``` | 36px
```large``` | 48px
```xlarge``` | 64px
```xxlarge``` | 100px

- [ ] Documentation should be updated with the margin values

### `padding`

| Source | element | property |
| :---         |     :---     |          :--- |
| Design specs (table)  | `padding-left`/ `padding-right`    | 36px / 60px    |
| Design specs (image)   | `padding-left` / `padding-right`      | 20px / 60px    |
| Implementation (React)   | `padding-left` / `padding-right`       | 20px / 36px    |
| Implementation (Angular)  | `padding-left` / `padding-right`       |   20px / 0px   |
| UI-Kit  | `padding-left` / `padding-right`      | 19px / 60px     |

- [ ] Fix padding in UI-Kit and documentation

**Comment by aweell** [comment]
Closed via #197
