### ISSUE TITLE
[Application layout] Documentation update

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#151]
## Padding Table header
Source Design guidelines - Application layout
For desktop - top - 64 px, bottom - 80 px, left/right - 15.6%
For Tablet - top - 48 px, bottom - 64 px, left/right - 9.6%
For Mobile - top - 36 px, bottom - 48 px, left/right - 6.4%
For header - height - 68 px, width - 100%
For footer - height - 128 px, width - 100%

Application Layout with side navigation - Side width - 300px, height 100%
Application Layout with secondary aside navigation - Aside width - 88 px, height 100%
Symmetrical layout - desktop - Top - 64px, bottom - 80px, left/right - 15.6%, 
Side column - width 270px, Top margin - 64 px, bottom margin - 80px

## Source Implementation (React) : 
min-height: 184px
margin-left: 297px

## Source Implementation (Angular) :
min-height: 200px;
padding-top: 30px;
padding-bottom: 60px

**Comment by aweell** [comment]
Hi @GauravMaurya0,

Since we need to review the overall layout documentation of the Design system we're going to wait until that work is completed.
