### ISSUE TITLE
[Box] Documentation update

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#152]
## Padding

Property | Value
-- | --
Padding right/left | 36px
Padding top/bottom | 36px/36px
Font size | 16px

## Margin
Property | Value
-- | --
Padding right/left | 36px
Padding top/bottom | 36px/36px
Font size | 16px

**Comment by aweell** [comment]
- [ ] Box documentation needs to be added

**Comment by aweell** [comment]
Closed via #183
