### ISSUE TITLE
[Card] Documentation update

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#155]
## Source design guideline
Property | Value
-- | --
Margin | 20px
Padding | 20px
Border Radius | 4px
Border thickness | 2px
Min. height | 220px
Min. width | 400px
Max. width | 100%
Image max. width | 140px
Space title-subtitle | 4px
Space main info to paragraph | 20px
Space actions to photo | 20px
Font size | ?

## Source Angular implementation
Padding, margin from title and subtitle, also border is not as per the guideline
Font color - # 000000
Font size - 14px

## Source React implementation
Padding, margin from title and subtitle, also border is not as per the guideline
Font color - #551A8B
Font size - 16px

**Comment by aweell** [comment]
Hello @GauravMaurya0,

The component card can have any content, React (showing a plain text and a link) and Angular (showing plain text) implementations have only examples of some content.

Since the rest of specs disparities are covered in #58, I close the issue.
