### ISSUE TITLE
Text input

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#157]
Use if 'Roboto, "Helvetica Neue", sans-serif' main text inputfield.

Design Specifications
---------------------

| Property | Value |
|--|--|
| Margin | 15px |
| Height (min) | 34px |
| Height (max) | 74px |
| Widht (min) | 230px |
| Widht (max) | 100% |
| Border thickness | 1px/2px |
| Font size (with text) | 16px |
| Font size smaller text | 12px |
| Font weight | Regular |
| Icon size | 18x18px |
| Distance between text and underline | 12px |
| Icon margin right side | 6px |
| Distance between text and underline (animated) | 6px |

Margin [**Implementation**]: 36px
height [**Implementation**]: 67.5px
width: [**Implementation**]: 240px
Smaller text [**Implementation**]: 15px

Margin [**image**]: 36px
Icon size [**image**]: 20x20px

**Comment by aweell** [comment]
Thanks @mnnaveenk,

This issue is already covered in #45
