### ISSUE TITLE
DXCDialog box is too small. Size cannot be given

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#16]
DXCDialog box is too small. Size cannot be given

Even in the desktop view, the dialog box is too small. If we include more elements on the dialog box, then the dialog box size remains same and scroll appears.

Though in attached screen, the content is less, but we have other places where it was a issue so we choose to develop a new page instead of a dialog box due to scrolling.

There should be a option to decide on the dialog box - like small/medium/large/custom size.

Please review and see if this is an issue. If there is a provision already by which we can change size please do tell.

![DialogBoxTooSmall](https://user-images.githubusercontent.com/72923647/101022976-1f380c00-3598-11eb-92ff-cac97a5b364f.jpg)

**Comment by jsardid** [comment]
Hello @ppurumala,

Guidelines already say: 
"Modals should be sized according to the content."
https://developer.dxc.com/design/components/dialog

So I understand there is not an issue with the guidelines, right?
If you have an issue with one of the Halstack libraries, please open it in the corresponding repository.

Thanks.
