### ISSUE TITLE
[Button] Component specs

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#160]
Button (angular) is aligned to center in the implementation of Sized Button using 'text-align: center' for the button container.

Button (react) with icon on the right example the icon is black in the default state and on the hover state.

**Comment by aweell** [comment]
Hello @mnnaveenk,

Regarding how the label is aligned in the button, all button examples are using the same CSS property to align the label when the button width increases, please provide more information in order to understand the issue.

Regarding the color of the icon, we already know there are more examples of this behavior, I'll add this to a single issue to cover the problem.

**Comment by mnnaveenk** [comment]
I found that as per the example below the result of the code sample when the size property is changed to ‘ **size=“fillParent”** ’ in the browsers full screen mode the check box is placed beyond the right margin making it almost invisible to the user.

![image](https://user-images.githubusercontent.com/83015051/117433363-08cc1d00-af49-11eb-9ac0-6176e3a2ed46.png)

**Browser output**
![image](https://user-images.githubusercontent.com/83015051/117433491-26998200-af49-11eb-9e07-a8dcb98abf91.png)

----------------------
I wanted to know if its ok for the text label to be in two or more lines in implementation of the checkbox when ‘size’ property of the component is changed to **‘ size=“small” ’** in the html code with **‘ margin=“medium” ’ or ‘ margin=”small” ’.**

![image](https://user-images.githubusercontent.com/83015051/117433955-b3444000-af49-11eb-935c-58812eff3a83.png)

**Browser output**
![image](https://user-images.githubusercontent.com/83015051/117434037-cbb45a80-af49-11eb-9401-77225c1ce181.png)

**Comment by mnnaveenk** [comment]
Pls refer the below images. the first 2 options are looking left aligned to the browser , but the 3rd option  looks center to the window.![image](https://user-images.githubusercontent.com/83015051/117438365-184e6480-af4f-11eb-85aa-e0c661ab0661.png)
![image](https://user-images.githubusercontent.com/83015051/117437274-97db3400-af4d-11eb-8185-4b1c16073ace.png)

![image](https://user-images.githubusercontent.com/83015051/117437869-6f076e80-af4e-11eb-89df-b073b40f4c15.png)

![image](https://user-images.githubusercontent.com/83015051/117437986-8f372d80-af4e-11eb-9dc1-9c4a2c43f499.png)

with the inspection below, shows 'align=center' for the button's container
![image](https://user-images.githubusercontent.com/83015051/117438387-20a69f80-af4f-11eb-8243-32d0319bf5ee.png)

**Comment by aweell** [comment]
Closed via #214
