### ISSUE TITLE
[Side Nav] Documentation update

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#162]
## Design tokens

Width | 300px
-- | --
Height (default) | auto - adapted to the content
Padding | 48px
Arrow display | true (default value)
Arrow distance | 50%

## For Mobile / Tablet
Property for sidenav | Value
-- | --
Width | 60%
Height (default) | auto - adapted to the content
Padding | 36px
Arrow display | true (it cannot be false)
Arrow distance | 50%

Source Angular implemented
Padding- 36px, it should be 48px
Font size is not similar in examples.

Source React implemented
Padding is not defined

**Comment by aweell** [comment]
**Implementations specs**

* React there's no default padding
* Angular is `medium` (36px)
* General sidenav used for components (in both implementations) uses 10px of `padding-left` in the sindenav-links, example instead uses 18px.
*General sidenav used in DEV Central has no `padding-left` in sidenav-links

**Documentation specs**

* `medium` should be set as default padding for the container.
