### ISSUE TITLE
[Tabs] Documentation update

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#163]
## Padding
Source design system - 12px 16px 12px 16 px
Height - 48px, width 90px or 360px

Angular implemented
Left16px, Right 16 px, Top & Bottom is not correct, please rctify them?
Height  46px, width 112px
Gap from left should be 48px

React implemented - 
The gap from the left should be 48px

**Comment by aweell** [comment]
Hello @GauravMaurya0,


* The values 90px and 360px are the min and max widths. 
   In react those values are correct, in angular the tab itself has a 160px min-width value. **I open an issue in the angular repository regarding this.**

* The height of the angular tabs is [already covered](https://github.com/dxc-technology/halstack-angular/issues/337) 

* The gap of 48px only applies to mobile devices.
