### ISSUE TITLE
Label is overlapping with the line below on the input field

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#17]
Label is overlapping with the line below on the input field

On DXCInput component, the size we have is medium. The label of that field is big enough to come in 2 lines.
when the label comes on 2nd line, its overlapping with the line below of the input field. 
We would like to make the size of the field as large, but in mobile view a horizontal scrollbar comes at bottom due to the large field.
Please Refer image, it will be more clear.
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/72923647/101035265-b608c680-35a0-11eb-9a5b-a8400b969f4c.png)

Can you please advice is this an issue or something we can take care at our end.

**Comment by jsardid** [comment]
Hello @ppurumala,

I think this is not an issue with the guidelines. Looks like an issue with the React implementation, right?
Can you open a new issue in the right repository and provide an isolated example so that we can reproduce it ourselves? 

Thanks.
