### ISSUE TITLE
[Select] Component Specs

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#170]
Default Select

in  Image
![image](https://user-images.githubusercontent.com/83015051/117485468-05a35200-af86-11eb-9a95-d7af1347e621.png)

As per Multi select Implementation
![image](https://user-images.githubusercontent.com/83015051/117485542-1784f500-af86-11eb-854c-53083e8ef6e9.png)
--------------
Font in the select dropdown is using 'Roboto font'
![image](https://user-images.githubusercontent.com/83015051/117486423-3f288d00-af87-11eb-9ea7-177f63ac6e52.png)
--------------
| Property for single | Value |
| -- | -- |
| Padding dropdown | 20px 10px 20px 20px |
| Height (default) | auto - adapted to the content |
| Item padding top/bottom | 10px |
| Font size | 16px |
| Font weight | Regular |

Padding [implementation]: 0px 16px

| Property for multiple | Value  |
| -- | -- |
| Padding dropdown | 10px 15px 20px 15px |
| Space chckbox/text | 15px |
| Item padding top/bottom | 10px |
| Font size | 16px |
| Font weight | Regular |
| Checkbox size | 20px x 20px |

Padding left in the implementation is not matching the design specs padding left is 10px 15px 10px 16px+15px

---------------

Select on focus in implementation is
select-focusColor: #005FCC;
![image](https://user-images.githubusercontent.com/83015051/117755394-bedd8280-b239-11eb-8c83-17a44259f13e.png)

in the image is black
![image](https://user-images.githubusercontent.com/83015051/117755542-08c66880-b23a-11eb-84e3-47145ff4228d.png)

In  React example for multiselect in the current example checkbox padding is 'padding: 10px 0px 10px 10px'
![image](https://user-images.githubusercontent.com/83015051/117756038-06184300-b23b-11eb-8fc4-b84107d7fe7e.png)
it should be changed to 'padding: 10px 10px 10px 0px' as shown in the image blow in the first option
![image](https://user-images.githubusercontent.com/83015051/117756930-b175c780-b23c-11eb-8268-00c04eaf728e.png)

in Angular implementation of multiple select for the checkboxes is with 'margin 10px 15px 10px  15px'
![image](https://user-images.githubusercontent.com/83015051/117758018-d53a0d00-b23e-11eb-9fed-89c6a6cbac6a.png)

Margins for the checkbox can be modified to 'margin 10px 15px 10px  0px' as shown in the result image below for the first option
![image](https://user-images.githubusercontent.com/83015051/117757342-8e97e300-b23d-11eb-91d4-ddfa5e5adf3b.png)

---------------

In all the Angular Implementation examples when any interaction is done on the select component the arrow is not interactive, it does not rotate according to action. pointing  up words in normal state when dropdown is enabled the arrow should point up, but as of now it always points down as shown in the image below.
![image](https://user-images.githubusercontent.com/83015051/117760834-f7825980-b243-11eb-8f3f-38f25d5e516a.png)

In React all examples work fine.

**Comment by aweell** [comment]
Closed via #199
* [React issue](https://github.com/dxc-technology/halstack-react/issues/312#issue-901265301)
* [Angular issue](https://github.com/dxc-technology/halstack-angular/issues/351#issue-901298455)
