### ISSUE TITLE
[Switch] Component specs

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#174]
in Angular 
----------
### Design Specs
| Property | Value |
|--|--|
| Margin right/left | 15px |
| Margin top/bottom | 10px |
| Switch bar | 44px |

switch bar [**Implementation**]: 36px
switch bar [**image**]: 44px

## Width

width [**Implementation**]: 35px
width [**image**]: 44px

## Margin

margin top/bottom [**Implementation**]: 15px
margin top/bottom [**Image & Design Specs**]: 15px

margin | value
-- | --
`xxsmall` | 6px
`xsmall` | 16px
`small` | 24px
`medium` default | 36px
`large` | 48px
`xlarge` | 64px
`xxlarge` | 100px

And also apply different values to each side of the component:
`top` `bottom` `left` `right`

## Font family

Font: 'Roboto, Helvitica Neue'

in React
--------
Margin [**Implementation**]: 3px
Switch bar [**Implementation**]: 36px

**Comment by aweell** [comment]
Thanks @mnnaveenk,

In addition, color specs should be reviewed

- [ ] Update: `disabledUncheckedTrackBackgroundColor` from specs table from #F2F2F2 TO #D9D9D9 + 0.12 opacity

**Comment by GomezIvann** [comment]
In addition to what @aweell said, this token should be reviewed:
- [ ] Update: `disabledFontColor` from specs table from #b1b1b1 to #000000 + 0.12 opacity

**Comment by aweell** [comment]
Closed via #179
