### ISSUE TITLE
No support to change font using theme of Platform

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#19]
**Is your feature request related to a problem? Please describe.**
As per our Product Owner, we want to give a feature to end customer that he can choose font/font-size on the complete application. It would be nice if we can support that from themes on Platform.

**Describe the solution you'd like**
Like we currently can choose the colors of different CDK components on platform, we would like a similar option to choose a font/font-size of all the text fields, radios, toggle, select boxes, date etc.

**Describe alternatives you've considered**
Probably we can achieve this using css over each components, but this would mean overwriting internal css of the cdk component - which we dont think is a good idea though

Please do tell if you need additional information on this request.
Thank you

**Comment by pwadhwani** [comment]
@peibolsang  Please share the corresponding Jira number for this issue.

**Comment by pwadhwani** [comment]
Please share updates on this issue.

**Comment by aweell** [comment]
Hello @ppurumala,

We have no plan in the near future to provide a theme input for `font-size` or `font-family` change.

**Comment by aweell** [comment]
Hello @ppurumala, @pwadhwani,

We are providing the font properties as theme inputs in the [advancedTheme](https://developer.dxc.com/tools/react/next/#/themeBuilder/advancedTheme). 

**Note that this theme implementation is at an early stage, still not documented, and is susceptible to change during the following sprints**.

**Comment by ppurumala** [comment]
Thank you @aweell.
Please provide the documentation for implementation of this advancedTheme whenever this is completely done and stable.

**Comment by pwadhwani** [comment]
Hi @aweell , Please let us know when will this be stable and ready to be consumed.

**Comment by sponnuswamydxc** [comment]
@jsardid Can you provide your latest updates on this issue ?

**Comment by mjayaraj2** [comment]
https://developer.dxc.com/tools/react/next/#/themeBuilder/advancedTheme As part of Themes change FONT has been implemented by CDK team
