### ISSUE TITLE
Request for assistiveText functionality for Select component... similar to InputText component

### ISSUE THREAD

**Issue by babdullah-at-dxc-dot-com** [dxc-technology/halstack-style-guide#203]
assistiveText feature is useful in displaying validation messages of a given component. It is available in Input-text and date components .. but not in Select component. Thus, this request.

**Comment by aweell** [comment]
Hello @babdullah-at-dxc-dot-com,

Helper text has been added to the select documentation draft and will be **available in the documentation** with release 3.1.2.

Closed via #204

**Comment by Kanahya-cdk** [comment]
@aweell To replicate the fixes we are using "@dxc-technology/halstack-angular": "next" version, We got fixes of this issue but validation message text appearing top of dropdown field. please refer the screenshot.
![dropdownissue](https://user-images.githubusercontent.com/85484716/120987748-85962500-c79b-11eb-8d23-f180b5460fa4.jpg)

**Comment by Kanhaya-DXC** [comment]
Just above comment written by me.

**Comment by jsardid** [comment]
@Kanhaya-DXC, this issue references the design guidelines (take into account that this is the design guidelines repository). 

For the angular implementation of this new guideline we have created https://github.com/dxc-technology/halstack-angular/issues/363 (it has been closed yesterday, and it should be available in the "next" release)
