### ISSUE TITLE
"Heading Text" XD kit specification is different for developer tool KIT 

### ISSUE THREAD

**Issue by pkumar589** [dxc-technology/halstack-style-guide#21]
The XD designer KIT Heading Text specifications are not synced with developer tool kit & it's vice versa.

Can we please have the same synchronization between 2 kit?

**Comment by peibolsang** [comment]
Please be more concrete with your issue report. What is the expected behavior? What solution would you like to see?

**Comment by jsardid** [comment]
Hello @pkumar589 ,

This the guidelines repository, and I understand you have an issue with one of component libraries (you are not saying which one), which apparently is not properly following the guidelines.

Can you please open an issue and provide further details in the corresponding components library's repository?

**Comment by peibolsang** [comment]
@pkumar589 please provide more details. I have reopened the issue

**Comment by pkumar589** [comment]
@peibolsang  I see it's been updated in the Developer kit & not much difference when compared with the designer kit. So this issue can be closed.
