### ISSUE TITLE
New XD Designer KIT doesn't have "Toggle" component

### ISSUE THREAD

**Issue by pkumar589** [dxc-technology/halstack-style-guide#22]
Developer Kit is having a "Toggle" component feature. 
Can we have the toggle design in the XD tool kit for designers.

**Comment by jsardid** [comment]
Hello @pkumar589,

That's right, we need to update the toggle guidelines with the new branding, and then include it in the Adobe XD kit.

Thanks for the feedback.

**Comment by pwadhwani** [comment]
@jsardid Prasanna has confirmed that its not in XD tool kit. Please share updates on this.

**Comment by aweell** [comment]
Toggle group component has been added to [UI Kit-Halstack_v2.1.1-beta](https://github.com/dxc-technology/halstack-style-guide/blob/release-2.1/ui-kit/UI%20Kit-Halstack_v2.1.1-beta.xd).**

The component follows the implementation visual design and behavior present in our [Angular](https://developer.dxc.com/tools/angular/2/#/components/toggleGroup) and [React](https://developer.dxc.com/tools/react/next/#/components/toggleGroup) libraries.

** _Note that this version of the UI Kit is open to modifications and the toggle group component guidelines are planned to be reviewed shortly._ 


![Toggle group](https://user-images.githubusercontent.com/44420072/109994851-00b7ed00-7d0e-11eb-8c76-039748eb35e6.png)
