### ISSUE TITLE
Alert with description (multiple line and color) + actions

### ISSUE THREAD

**Issue by pkumar589** [dxc-technology/halstack-style-guide#23]
Developer Kit doesn't have below option in their tool.

Can we please have same what is provided in designer XD Kit?
Attached image for your reference

![image](https://user-images.githubusercontent.com/75477033/102087040-fd177700-3e3e-11eb-8938-c332b48cf080.png)

**Comment by jsardid** [comment]
@pkumar589,

If one of the libraries is not properly following the guidelines, please open an issue in the corresponding library's repository.

Thanks!
