### ISSUE TITLE
Label before not available in design kit for Radio Button component

### ISSUE THREAD

**Issue by pkumar589** [dxc-technology/halstack-style-guide#24]
In designer XD kit we have radio button before the label but in the developer kit, they have label position before & after a radio button.
Can we have consistency between the 2 kit's, please?

Attached XD kit reference image.
![image](https://user-images.githubusercontent.com/75477033/102088034-59c76180-3e40-11eb-9b42-d17f4bda516b.png)

**Comment by jsardid** [comment]
Hello @pkumar589,

This the guidelines repository, and I understand you have an issue with one of component libraries (you are not saying which one), which apparently is not properly following the guidelines.

Can you please open an issue in the corresponding components library's repository?

**Comment by pwadhwani** [comment]
@jsardid  Please share Jira ticket for this issue.

**Comment by aweell** [comment]
Label before for Radio button component has been added to UI Kit-Halstack_v2.1.1-beta.**

  ** Note that this version of the UI Kit is open to modifications and the Radio button component guidelines are planned to be reviewed shortly.

![Screenshot 2021-03-05 at 09 06 05](https://user-images.githubusercontent.com/44420072/110086076-369eb500-7d92-11eb-8c56-30cb94940270.png)
