### ISSUE TITLE
"Tabs with Icon & label" component missing in developer kit

### ISSUE THREAD

**Issue by pkumar589** [dxc-technology/halstack-style-guide#25]
The developer said they don't have this option in their tool kit.

Can we please have this component for developers?
Attached image for your reference

![image](https://user-images.githubusercontent.com/75477033/102089082-c4c56800-3e41-11eb-9bc3-e50bc6eed2d6.png)

**Comment by peibolsang** [comment]
The tabs component is available in the CDK already: https://developer.dxc.com/tools/react/1/#/components/tabs

If this is referring to another type of issue, please comment
