### ISSUE TITLE
Screen names are not visible on the wizard due to very light text color

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#26]
**Describe the bug**
Screen names are not visible on the wizard due to very light text color.
We have implemented DXCWizard in our application, the screen names is not correctly visible. We understand that the screens are yet not visited so the text is disabled, but the text should be bit more greyish, currently is very near to white and not readable.
Could you please change the disable text, to more greyish.

![wizard](https://user-images.githubusercontent.com/72923647/102305297-9ea8e080-3f85-11eb-9e1a-91fc51bc06bc.jpg)

**To Reproduce**
Implement Wizard and if there are 5 steps in it, see the screen names of last 4 if very faint colored.

**Comment by jsardid** [comment]
Hello @ppurumala, 

I think guidelines are already darker than the screenshot you are providing:
https://developer.dxc.com/design/components/wizard

If this is an issue with a library and not with the guidelines, please open it in the corresponding library's repository.

Thanks.
