### ISSUE TITLE
[File-input] Component design update

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#27]
<DxcUpload> component is not responsive in mobile view

The <DxcUpload> component view is distorted in mobile view. Attached are the screenshots of the mobile views:
[DxcUpload mobile view.zip](https://github.com/dxc-technology/halstack-style-guide/files/5835434/DxcUpload.mobile.view.zip)

Can you please suggest if this is a genuine issue or is it something we can handle at our end?

**Comment by pwadhwani** [comment]
@peibolsang Could you please share updates on this and if any jira ticket created please share the number.

**Comment by pwadhwani** [comment]
Please share updates on this issue.

**Comment by pwadhwani** [comment]
@aweell @jsardid Could you please provide updates on this issue.

**Comment by aweell** [comment]
Hello @ppurumala, @pwadhwani 

We are aware of the upload behavior in terms of responsiveness. The component is planned to be reviewed, but understand that we need to set priorities. Your feedback will be added to the component review. I set the issue status as "waiting for review" until then.

**Comment by pwadhwani** [comment]
@aweell Could you please share ETC on this ticket.

**Comment by aweell** [comment]
We're currently working on the [review of the component](https://github.com/dxc-technology/halstack-style-guide/tree/draft-3.7.0-upload/guidelines/components/upload), the component documentation status is `draft`.

**Comment by aweell** [comment]
## Epic description

* Review the design of the component update to provide a more compact, usable, and easy to integrate into the UI layout.
* The component is planned to have the following variants: `file`, `filedrop`, and `droparea`.
* Design of the file items list to accommodate file information feedback for single and multiple uploads

Current draft of the component: [Upload documentation](https://github.com/dxc-technology/halstack-style-guide/tree/draft-3.7.0-upload/guidelines/components/upload)

### Tasks

- [ ] [Upload] Component documentation update
- [ ] [Upload] UI-Kit component update

**Comment by aweell** [comment]
Closed via #623

**Comment by mjayaraj2** [comment]
New [FileInput](https://developer.dxc.com/halstack/next/components/file-input/) component.
