### ISSUE TITLE
DXC Toggle Group improvements

### ISSUE THREAD

**Issue by Tarun-DXC** [dxc-technology/halstack-style-guide#273]
**Is your feature request related to a problem? Please describe.**
In toggle groups, when the toggle option is of type icon, there are couple of issues
1. Icons are not always self-explanatory. Need capability to show text with icons so that business users may identify better. Image below contains different insurance types shown as icon toggle. It is very difficult for a business user to understand which icon corresponds to which insurance. Hover text or text next to icon would be better

![image](https://user-images.githubusercontent.com/80850088/122791249-b10a2b00-d2d6-11eb-86fe-fb8d8d967035.png)

2. toggles should be allowed to have spacing in between in case of icons. Otherwise, they give the feel that it is a single image(refer to above image)

**Describe the solution you'd like**
Problem and proposal described above

**Describe alternatives you've considered**
Tried using a custom component during design, which was not approved by CDK team as it was not valid use case

**Additional context**

**Add Labels**
dxc-toggle

**Comment by aweell** [comment]
Hi @Tarun-DXC,

We have updated our documentation based on the feedback provided:

* Allow having label and icon simultaneously
* Each element on the google group container is horizontally stacked with 4px gutters

You can review the [toggle documentation draft here](https://github.com/dxc-technology/halstack-style-guide/blob/component-toggle/guidelines/components/toggle/README.md)

Please let us know if the component changes meet your expectations and thanks for providing your feedback! :smiley:

**Note**: _The draft still needs technical review, minor details are expected to change_

**Comment by aweell** [comment]
Closed via #613
