### ISSUE TITLE
Grid layout

### ISSUE THREAD

**Issue by mmascord** [dxc-technology/halstack-style-guide#29]
Currently there is no way to layout components with the CDK as it does not have any kind of Grid layout.

Are there any plans to implement such layout components?

Currently to layout the components it is necessary to use either Bootstrap or Material-UI layout components such as Grid.  Obviously this tightly couples any CDK app to Bootstrap or Material-UI.

**Comment by aweell** [comment]
We are currently working on the grid and layout documentation so the first draft will be ready in the next sprints.

**Comment by aweell** [comment]
Thanks @mmascord,

As the Grid documentation is been covered in #48 please provide any feedback there in order to help us improve our design docs!
