### ISSUE TITLE
[Card] Color specs update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#296]

**Comment by mnnaveenk** [comment]
## React

--
   

## Angular

--card-backgroundColor": globalTokens.white

## Card color specs table


|   Component token     |   Element                     |   Core token                  |   Value       |
| --------------------- | ----------------------------- | ----------------------------- | ------------- |
|   `backgroundColor`   |   Container                   |   `Hal-White`                 |   `#ffffff`   |

**Comment by aweell** [comment]
Closed via #415
