### ISSUE TITLE
[Dialog] Color specs update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#298]
## React   

    overlayColor: globalTokens.black,
    scrollBarThumbColor: globalTokens.darkGrey,
    scrollBarTrackColor: globalTokens.lightGrey,
    backgroundColor: globalTokens.white,
    fontColor: globalTokens.black,
    closeIconBackgroundColor: "none",
    closeIconBorderColor: "none",
    boxShadowColor: "rgba(0, 0, 0, 0.2)",

## Dialog color specs table

|   Component token                     |   Element                               |   Core token                              |   Value                          |
|  :-----------------------------  |  :-------------------------  |  :---------------------------  |  :--------------------  |
|   `overlayColor`                           |   Overlay                                |   `black`                                   |   `#000000`                |
|   `scrollBarThumbColor`            |   Scrollbar: Thumb                |   `grey-700`                             |   `#666666`                |
|   `scrollBarTrackColor`               |   Scrollbar: track                   |   `grey-200`                             |   `#e6e6e6`                |
|   `backgroundColor`                   |   Scrollbar: container           |   `white`                                    |   `#ffffff`                      |
|   `fontColor`                                 |   Title                                     |   `black`                                    |   `#000000`                |
|   `closeIconColor`                       |   Icon close                            |   `black`                                    |   `#000000`                |
|   `boxShadowColor`                    |   Container shadow              |   -                                               |   `rgba(0, 0, 0, 0.2)`   |
|   `closeIconBackgroundColor`   |   Icon close background      |   `none`                                     |   none                           |
|   `closeIconBorderColor`            |   Icon close border               |   `none`                                     |   none                           |

**Comment by mnnaveenk** [comment]
## React

overlayColor: globalTokens.black
scrollBarThumbColor: globalTokens.darkGrey
scrollBarTrackColor: globalTokens.lightGrey
backgroundColor: globalTokens.white
fontColor: globalTokens.black
closeIconBackgroundColor: "none"
closeIconBorderColor: "none"
closeIconColor: globalTokens.black
boxShadowColor: "rgba(0, 0, 0, 0.2)"
   

## Angular

  "--dialog-overlayColor": globalTokens.black,
  "--dialog-backgroundColor": globalTokens.white,
  "--dialog-scrollBarThumbColor": globalTokens.darkGrey,
  "--dialog-scrollBarTrackColor": globalTokens.lightGrey,

## Card color specs table


|   Component token             |   Element                 |   Core token                  |   Value                   |
| ----------------------------- | ------------------------- | ----------------------------- | ------------------------- |
|   `overlayColor`              |   Container               |   `Hal-Black`                 |   `#000000`               |
|   `scrollBarThumbColor`       |   Scrollbar: Thumb        |   `Hal-Red-S-41`              |   `#d0011b`               |
|   `scrollBarTrackColor`       |   Scrollbar: track        |   `globalTokens.lightGrey`    |   `#D9D9D9`               |
|   `backgroundColor`           |   Scrollbar: container    |   `Hal-White`                 |   `#ffffff`               |
|   `fontColor`                 |   Text                    |   `Hal-Black`                 |   `#000000`               |
|   `closeIconBackgroundColor`  |   -                       |   -                           |   -                       |
|   `closeIconBorderColor`      |   -                       |   -                           |   -                       |
|   `closeIconColor`            |   closeIcon               |   `Hal-Black`                 |   `#000000`               |
|   `boxShadowColor`            |   container shadow        |   -                           |   `rgba(0, 0, 0, 0.2)`    |

**Comment by aweell** [comment]
Closed via #442

**Comment by aweell** [comment]
Closed via #442
