### ISSUE TITLE
Application name in header component

### ISSUE THREAD

**Issue by pkumar589** [dxc-technology/halstack-style-guide#30]
It's a business requirement to have "Application Name" in the header component. This new request will reduce the space under the header which was previously occupied by application name.

**Add Labels**
Add any applicable labels like related components, services, team or project reporting this new feature... etc
<img width="813" alt="Header requirements" src="https://user-images.githubusercontent.com/75477033/101152412-0dfb0800-3649-11eb-90af-563cb53effc7.PNG">

**Comment by pwadhwani** [comment]
@jsardid  Please share Jira ticket for this issue.

**Comment by aweell** [comment]
Until the review of the documentation for the header component, the application name can be added as [custom content](https://developer.dxc.com/design/components/header).

**Comment by ppurumala** [comment]
we are not able to achieve it through the documentation provided at -> DXC React Components
This custom content modification is something already there or we have to write a custom code for that?
