### ISSUE TITLE
[Tag] Color specs update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#306]

**Comment by GomezIvann** [comment]
Changes made on the Tag advanced tokens:

- [ ] `fontFamily` token added.
- [ ] `fontColor` token added.
- [ ] `fontSize` token added.
- [ ] `fontWeight` token added.

**Comment by GauravMaurya0** [comment]
## React
iconColor: globalTokens.white,

## Angular
"--tag-backgroundColor": globalTokens.white,

## Tag color specs table

| Component token                         | Element       | Core token | Value |
| -----------------------------   | ----------- | -------- | --------- |
| `backgroundColor` | Fill | `Hal-White` | `#ffffff` |
