### ISSUE TITLE
[Wizard] Color specs update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#308]
## React

disabledBackgroundColor: globalTokens.lightGrey
disabledFontColor: globalTokens.darkGrey
stepContainerFontColor: globalTokens.black
stepContainerSelectedFontColor: globalTokens.white
stepContainerSelectedBackgroundColor: globalTokens.purple
stepContainerBackgroundColor: globalTokens.white
labelFontColor: globalTokens.darkGrey
labelActiveFontColor: globalTokens.black
descriptionFontColor: globalTokens.darkGrey
descriptionActiveFontColor: globalTokens.black
circleBorderColor: globalTokens.black
circleSelectedBorderColor: globalTokens.purple
circleDisabledBorderColor: globalTokens.lightGrey
separatorColor: globalTokens.lightGrey
focusColor: globalTokens.blue

## Angular

"--wizard-selectedBackgroundColor": globalTokens.purple,
"--wizard-selectedFont": globalTokens.white,
"--wizard-borderColor": globalTokens.black,
"--wizard-fontColor": globalTokens.inherit,
"--wizard-lineColor": globalTokens.lightGrey,
"--wizard-disabledBackground": globalTokens.lightGrey,
"--wizard-disabledFont": globalTokens.darkGrey,
"--wizard-focusColor": globalTokens.blue,

## Wizard color specs table

| Component token                          | Element                            | Core token             | Value            |
| :--------------------------------------- | :--------------------------------- | :--------------------- | :--------------- |
| `stepperFontColor`                              | Stepper text                       | `color-black`          | `#000000`           |
| `selectedStepperFontColor`               | Stepper:selected text              | `color-white`          | `#ffffff`           |
| `unvisitedStepperFontColor`              | Stepper:unvisited text             | `color-grey-700`       | `#666666`           |
| `disabledStepperFontColor`               | Stepper:disabled text              | `color-grey-500`       | `#999999`           |
| `stepperBackgroundColor`                 | Stepper background                 | `color-white`          | `#ffffff`           |
| `selectedStepperBackgroundColor`         | Stepper:selected background        | `color-purple-700`     | `#5f249f`           | 
| `unvisitedStepperBackgroundColor`        | Stepper:unvisited background       | `color-grey-700`       | `#666666`          | 
| `disabledStepperBackgroundColor`         | Stepper:disabled background        | `color-grey-100`       | `#f2f2f2`           |
| `stepperBorderColor`                     | Stepper border                     | `coor-black`           | `#000000`          |
| `selectedStepperBorderColor`             | Stepper:selected border            | `color-purple-700`     | `#5f249f`           |
| `unvisitedStepperBorderColor`            | Stepper:unvisited border           | `color-grey-700`       | `#666666`           |
| `disabledStepperBorderColor`             | Stepper:disabled border            | `color-grey-100`       | `#f2f2f2`           |
| `labelFontColor`                         | Label                              | `color-black`          | `#000000`           |
| `activeLabelFontColor`                   | Label:active                       | `color-black`          | `#000000`           |
| `disabledLabelFontColor`                 | Label:disabled                     | `color-grey-500`       | `#999999`           |
| `helperTextFontColor`                    | Helper text                        | `color-black`          | `#000000`           |
| `helperTextActiveFontColor`              | Helper text: active                | `color-black`          | `#000000`           |
| `separatorColor`                         | Separator                          | `color-grey-700`       | `#666666`           |
| `focusColor`                             | Focus outline                      | `color-blue-600`       | `#0095ff`           |

**Comment by mnnaveenk** [comment]
## React

disabledBackgroundColor: globalTokens.lightGrey
disabledFontColor: globalTokens.darkGrey
stepContainerFontColor: globalTokens.black
stepContainerSelectedFontColor: globalTokens.white
stepContainerSelectedBackgroundColor: globalTokens.purple
stepContainerBackgroundColor: globalTokens.white
labelFontColor: globalTokens.darkGrey
labelActiveFontColor: globalTokens.black
descriptionFontColor: globalTokens.darkGrey
descriptionActiveFontColor: globalTokens.black
circleBorderColor: globalTokens.black
circleSelectedBorderColor: globalTokens.purple
circleDisabledBorderColor: globalTokens.lightGrey
separatorColor: globalTokens.lightGrey
focusColor: globalTokens.blue

## Angular

"--wizard-selectedBackgroundColor": globalTokens.purple,
"--wizard-selectedFont": globalTokens.white,
"--wizard-borderColor": globalTokens.black,
"--wizard-fontColor": globalTokens.inherit,
"--wizard-lineColor": globalTokens.lightGrey,
"--wizard-disabledBackground": globalTokens.lightGrey,
"--wizard-disabledFont": globalTokens.darkGrey,
"--wizard-focusColor": globalTokens.blue,

## Wizard color specs table


|   Component token                         |   Element                       |   Core token                  |   Value                   |
| ----------------------------------------- | ------------------------------- | ----------------------------- | ------------------------- |
|   `disabledBackgroundColor`               |   Disabled Container            | `globalTokens.lightGrey`      |   `#D9D9D9`               |
|   `disabledBackground` |(angular)         |   Disabled Container            | `globalTokens.lightGrey`      |   `#D9D9D9`               |
|   `disabledFontColor`                     |   Disabled text                 | `Hal-Grey-S-40`               |   `#666666`               |
|   `disabledFont` (angular)                |   Step Container Text           | `Hal-Grey-S-40`               |   `#666666`               |
|   `stepContainerFontColor`                |   Step Container Text           | `Hal-Black`                   |   `#000000`               |
|   `stepContainerSelectedFontColor`        |   Step Container: selected Text | `Hal-White`                   |   `#ffffff`               |
|   `selectedFont` (angular)                |   Step Container: selected Text | `Hal-White`                   |   `#ffffff`               |
|   `stepContainerSelectedBackgroundColor`  |   Step Container: selected      | `globalTokens.purple`         |   `#6f2c91`               |
|   `selectedBackgroundColor` (angular)     |   Step Container: selected      | `globalTokens.purple`         |   `#6f2c91`               |
|   `stepContainerBackgroundColor`          |   Step Container                | `Hal-White`                   |   `#ffffff`               |
|   `labelFontColor`                        |   Label                         | `Hal-Grey-S-40`               |   `#666666`               |
|   `FontColor` (angular)                   |   Label                         | `globalTokens.inherit`        |   `inherit`               |
|   `labelActiveFontColor`                  |   Label: active                 | `Hal-Black`                   |   `#000000`               |
|   `descriptionFontColor`                  |   Description Label             | `Hal-Grey-S-40`               |   `#666666`               |
|   `descriptionActiveFontColor`            |   Description Label: active     | `Hal-Black`                   |   `#000000`               |
|   `circleBorderColor`                     |   Container Border              | `Hal-Black`                   |   `#000000`               |
|   `borderColor` (angular)                 |   Container Border              | `Hal-Black`                   |   `#000000`               |
|   `circleSelectedBorderColor`             |   Container Border: Selected    | `globalTokens.purple`         |   `#6f2c91`               |
|   `circleDisabledBorderColor`             |   Container Border: Disabled    | `globalTokens.lightGrey`      |   `#D9D9D9`               |
|   `separatorColor`                        |   Container                     | `globalTokens.lightGrey`      |   `#D9D9D9`               |
|   `lineColor` (angular)                   |   Container                     | `globalTokens.lightGrey`      |   `#D9D9D9`               |
|   `focusColor`                            |   Container                     | `globalTokens.blue`           |   `#005FCC`               |

**Comment by GomezIvann** [comment]
Changes made on the Wizard advanced tokens:

- [ ] `circleSelectedWidth` renamed as `selectedCircleWidth`.
- [ ] `circleSelectedHeight` renamed as `selectedCircleHeight`.
- [ ] `circleSelectedBorderThickness` renamed as `selectedCircleBorderThickness`.
- [ ] `circleSelectedBorderStyle` renamed as `selectedCircleBorderStyle`.
- [ ] `circleSelectedBorderRadius` renamed as `selectedCircleBorderRadius`.
- [ ] `circleSelectedBorderColor` renamed as `selectedCircleBorderColor`.
- [ ] `circleDisabledWidth` renamed as `disabledCircleWidth`.
- [ ] `circleDisabledHeight` renamed as `disabledCircleHeight`.
- [ ] `circleDisabledBorderThickness` renamed as `disabledCircleBorderThickness`.
- [ ] `circleDisabledBorderStyle` renamed as `disabledCircleBorderStyle`.
- [ ] `circleDisabledBorderRadius` renamed as `disabledCircleBorderRadius`.
- [ ] `circleDisabledBorderColor` renamed as `disabledCircleBorderColor`.
- [ ] `labelActiveFontColor` renamed as `visitedLabelFontColor`.
- [ ] `descriptionActiveFontColor` renamed as `visitedDescriptionFontColor`.

**Comment by aweell** [comment]
Closed via #490
