### ISSUE TITLE
Label not visible on Table Header with Black background

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#31]
**Describe the bug**
Label not visible on Table Header with Black background
<DxcCheckbox labelPosition="after" label="Exclude Voided Notes" />
![TextNotVisible](https://user-images.githubusercontent.com/72923647/106595811-21a7e980-657a-11eb-8c06-6d81622eb477.jpg)

The theme is coming from Platform UI configurator, and its currently black. The label is not visible, as it is too black color.

Please let us know if something which we can do at our end? 

**To Reproduce**
We have used <DXCTable>, the theme is coming from Platform. Its black color of header, hence the text is not visible of the checkbox.

**Comment by aweell** [comment]
Since this issue is already solved, I set it as closed.
