### ISSUE TITLE
[Upload] Color specs update

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#310]

**Comment by mnnaveenk** [comment]
## React

fontFamily: globalTokens.type_sans
shadowColor: globalTokens.lightWhite
scrollBarThumbColor: globalTokens.darkGrey
scrollBarTrackColor: globalTokens.lightGrey
errorColor: globalTokens.red
backgroundColor: globalTokens.white
draggingAreaBackgroundColor: globalTokens.lightWhite
dragAndDropIconColor: globalTokens.black
dragAndDropTitleFontColor: globalTokens.black
dragAndDropTextDescriptionFontColor: globalTokens.darkGrey
dragAndDropDraggingStateIconColor: globalTokens.darkGrey
dragAndDropTextDraggingStateFontColor: globalTokens.darkGrey
dragAndDropAreaIconColor: globalTokens.darkGrey
dragAndDropAreaTextFontColor: globalTokens.darkGrey
fileDeleteIconColor: globalTokens.black
fileHoverColor: globalTokens.darkWhite
fileUnderlineColor: globalTokens.lightGrey
fileNameFontColor: globalTokens.black
fileTypeFontColor: globalTokens.darkGrey
fileUploadedIconColor: globalTokens.lightGrey
filesUploadedTitleFontColor: globalTokens.black
filesUploadedSubtitleFontColor: globalTokens.darkGrey  

## Angular

"--upload-fontColor": globalTokens.darkGrey,
"--upload-shadowColor": globalTokens.lightWhite,
"--upload-backgroundDragColor": globalTokens.lightWhite,
"--upload-accentColor": globalTokens.lightGrey,
"--upload-fileHoverColor": globalTokens.darkWhite,
"--upload-scrollBarThumbColor": globalTokens.darkGrey,
"--upload-scrollBarTrackColor": globalTokens.lightGrey,
"--upload-errorColor": globalTokens.darkRed,

## Upload color specs table


|   Component token                         |   Element                 |   Core token                  |   Value                   |
| ----------------------------------------- | ------------------------- | ----------------------------- | ------------------------- |
|   `shadowColor`                           |   container shadow        |   -                           |   `rgba(0, 0, 0, 0.2)`    |
|   `scrollBarThumbColor`                   |   Scrollbar: Thumb        |   `Hal-Grey-S-40`             |   `#666666`               |
|   `scrollBarTrackColor`                   |   Scrollbar: track        |   `globalTokens.lightGrey`    |   `#D9D9D9`               |
|   `errorColor`                            |   label                   |   `Hal-Red-S-41`              |   `#D0011B`               |
|   `backgroundColor`                       |   Container               |   `Hal-White`                 |   `#ffffff`               |
|   `draggingAreaBackgroundColor`           |   Container               |   `Hal-Grey-L-95`             |   `#f2f2f2`               |
|   `dragAndDropIconColor`                  |   icon                    |   `Hal-Black`                 |   `#000000`               |
|   `dragAndDropTitleFontColor`             |   icon label              |   `Hal-Black`                 |   `#000000`               |
|   `dragAndDropTextDescriptionFontColor`   |   icon                    |   `Hal-Grey-S-40`             |   `#666666`               |
|   `dragAndDropDraggingStateIconColor`     |   icon                    |   `Hal-Grey-S-40`             |   `#666666`               |
|   `dragAndDropTextDraggingStateFontColor` |   label                   |   `Hal-Grey-S-40`             |   `#666666`               |
|   `dragAndDropAreaIconColor`              |   icon                    |   `Hal-Grey-S-40`             |   `#666666`               |
|   `dragAndDropAreaTextFontColor`          |   label                   |   `Hal-Grey-S-40`             |   `#666666`               |
|   `fileDeleteIconColor`                   |   file delete icon        |   `Hal-Black`                 |   `#000000`               |
|   `fileHoverColor`                        |   file container: hover   |   `globalTokens.darkWhite`    |   `#eeeeee`               |
|   `fileUnderlineColor`                    |   file cunderline         |   `globalTokens.lightGrey`    |   `#D9D9D9`               |
|   `fileNameFontColor`                     |   file label              |   `Hal-Black`                 |   `#000000`               |
|   `fileTypeFontColor`                     |   file type labeln        |   `Hal-Grey-S-40`             |   `#666666`               |
|   `fileUploadedIconColor`                 |   file upload icon        |   `globalTokens.lightGrey`    |   `#D9D9D9`               |
|   `filesUploadedTitleFontColor`           |   upload title            |   `Hal-Black`                 |   `#000000`               |
|   `filesUploadedSubtitleFontColor`        |   upload sub title        |   `Hal-Grey-S-40`             |   `#666666`               |

**Comment by GomezIvann** [comment]
Changes made on the Upload advanced tokens:

- [ ] `dragAndDropTextDescriptionFontTextTransform` renamed as `dragAndDropDescriptionFontTextTransform`.
- [ ] `dragAndDropTextDescriptionFontColor` renamed as `dragAndDropDescriptionFontColor`.
- [ ] `dragAndDropTextDraggingStateFontTextTransform` renamed as `dragAndDropDraggingStateFontTextTransform`.
- [ ] `dragAndDropTextDraggingStateFontColor` renamed as `dragAndDropDraggingStateFontColor`.

**Comment by aweell** [comment]
[Upload component draft](https://github.com/dxc-technology/halstack-style-guide/tree/draft-3.7.0-upload/guidelines/components/upload) updated for review.
