### ISSUE TITLE
[Input-text] Update text-input documentation

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#326]
## Story description

Update input-text documentation page with the latest component changes

### General 

- [x] Remove show and hide content section
- [x] Remove number section

### Update variants section

- [x] Remove `text-area` as a component variant

### Update component images

- [x] Update variants image
- [x] Update anatomy image
- [x] Update clearing content image

### Update color section

- [x] Add component base tokens
- [x] Divide between on-ligh and on-dark specs
- [x] Add tokens for leading and trailing icons, prefix, and suffix elements
- [x] Add token for prefix/suffix divider
- [x] Add tokens for component actions (default and custom)
- [x] Add tokens for custom links in helper text

## [3.5.0] Updates

- [x] Remove link and tooltip trigger from "Helper text" section
- [x] Update `font-size` values in `systemMessage` tokens
- [x] Add value tokens

### General 

- [ ] Add use case explanation for clearing option

### Component specs

- [x] Add `disabledPlaceholderFontColorOnDark` token
- [x] Update token naming when applied to font
- [x] Rename `activeActionOutlineColor` to `activeActionBackgroundColor`
- [x] Update value for refix and suffix tokens to `Hal-Grey-S-40`
- [x] Fix typo in `SytemMessageFontColor` token
- [x] Remove backticks from table value column
- [x] Add `prefix`/`suffix` `:disabled` tokens
- [x] Add custom actions `:disabled` tokens
- [x] Remove `leadingIcon` and `trailingIcon` tokens

### Images

- [x] Update component images with proper spacing specifications
- [x] Update `iconActionBackgroundColorOnDark` states token values

**Comment by aweell** [comment]
Closed via #365

**Comment by GomezIvann** [comment]
Color token doubts:

1. `disabledLabelColor` shouldn't be named as `disabledLabelFontColor`?
2. `placeholderColor` shouldn't be named as `placeholderFontColor`? Same for its disabled and onDark counterparts.
3. `outlineEnabledColor` shouldn't be named as `enabledOutlineColor`?
4. Could be interesting to add a new token `listOptionFontColor` for the autosuggest list options, do you agree?

**Comment by aweell** [comment]
Fixed (1, 2, 3, 5 & 6) 👍🏼 

> 4. Could be interesting to add a new token `listOptionFontColor` for the autosuggest list options, do you agree?

This token is present in the [autocomplete section specs](https://github.com/dxc-technology/halstack-style-guide/blob/component-input/guidelines/components/text-input/README.md#specs-1)

**Comment by GomezIvann** [comment]
More color token doubts:

- Should we add a `disabledPlaceholderFontColorOnDark` token as the rest of the input elements had it disabledOnDark token (see `disabledLabelColorOnDark`, `disabledHelperTextFontColorOnDark`, etc).

**Comment by GomezIvann** [comment]
Misprints i found:

On-dark > Interactive
- `disabledActionColorOnDark` instead of `disabledActionColor`.
- `disabledSuffixColorOnDark` value is _Hal-Grey-S-75_ which doesn't exist. Shouldn't it be _Hal-Grey-L-75_ instead?
- `disabledPrefixColorOnDark` value is _Hal-Grey-S-75_ which doesn't exist. Shouldn't it be _Hal-Grey-L-75_ instead?

**Comment by aweell** [comment]
Closed via #458 and #459
