### ISSUE TITLE
[Box] Color specs update

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-style-guide#331]
Changes made on the Box advanced tokens:

- [ ] `fontFamily` token removed.
- [ ] `fontWeight` token removed.
- [ ] `fontSize` token removed.
- [ ] `fontColor` token removed.

**Comment by GauravMaurya0** [comment]
## React

backgroundColor: globalTokens.white,
fontColor: globalTokens.black,
borderColor: "transparent",
noneShadowDepthShadowColor: "transparent",
oneShadowDepthShadowColor: "#00000033",
twoShadowDepthShadowColor: "#00000033",


## Angular

"--box-backgroundColor": globalTokens.white,


## Box color specs table
| Component token                         | Element       | Core token | Value |
| -----------------------------   | ----------- | -------- | --------- |
| `backgroundColor` | Fill | `Hal-White` | `#ffffff` |
| `FontColor` | Label | `Hal-Black` | `#000000` |
| `borderColor` | Border | - | `transparent` |
| `noneShadowDepthShadowColor` | shadow | - | `transparent` |
| `oneShadowDepthShadowColor` | shadow | `Hal-Blue-D-20` | `#003c66` |
| `twoShadowDepthShadowColor` | shadow | `Hal-Blue-D-20` | `#003c66` |

**Comment by aweell** [comment]
Closed via #609
