### ISSUE TITLE
[Heading] Color specs update

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-style-guide#356]
Changes made on the Heading advanced tokens:

- [x] `fontColorBase` token removed.
- [x] `fontFamilyBase` token removed.
- [x] `level1FontColor` has a new value: `inherit`.
- [x] `level1FontFamily` has a new value: `Open Sans, sans-serif`.
- [x] `level2FontColor` has a new value: `inherit`.
- [x] `level2FontFamily` has a new value: `Open Sans, sans-serif`.
- [x] `level3FontColor` has a new value: `inherit`.
- [x] `level3FontFamily` has a new value: `Open Sans, sans-serif`.
- [x] `level4FontColor` has a new value: `inherit`.
- [x] `level4FontFamily` has a new value: `Open Sans, sans-serif`.
- [x] `level5FontColor` has a new value: `inherit`.
- [x] `level5FontFamily` has a new value: `Open Sans, sans-serif`.

**Comment by aweell** [comment]
Closed since no changes needed in heading component documentation
