### ISSUE TITLE
[Textarea] Color specs update

### ISSUE THREAD

**Issue by GomezIvann** [dxc-technology/halstack-style-guide#378]
Changes made on the Textarea advanced tokens:

- [ ] `assistiveTextFontFamily` token removed.
- [ ] `labelFontFamily` token removed.
- [ ] `valueFontFamily` token removed.
- [ ] `customContentFontFamily` renamed as `valueFontFamily`.
- [ ] `customContentFontSize` renamed as `valueFontSize`.
- [ ] `customContentFontStyle` renamed as `valueFontStyle`.
- [ ] `customContentFontWeight` renamed as `valueFontWeight`.
- [ ] `customContentFontColor` renamed as `valueFontColor`.
- [ ] `customContentFontColorOnDark` renamed as `valueFontColorOnDark`.
- [ ] `customContentLetterSpacing` renamed as `valueLetterSpacing`.
- [ ] `customContentLineHeight` renamed as `valueLineHeight`.
- [ ] `disabledFontColor` renamed as `disabledColor`.
- [ ] `disabledFontColorOnDark` renamed as `disabledColorOnDark`.
- [ ] `assistiveTextLetterSpacing` has now a value of `0.03333em`.
- [ ] `labelLetterSpacing` has now a value of `0.00938em`.
- [ ] New `fontFamily` token added with value: `Open Sans, sans-serif`.
- [ ] New `underlineColor` token added with value: `#000000`.
- [ ] New `underlineColorOnDark` token added with value: `#ffffff`.
- [ ] New `underlineFocusColor` token added with value: `#000000`.
- [ ] New `underlineFocusColorOnDark` token added with value: `#ffffff`.
- [ ] New `underlineThickness` token added with value: "1px".

**Comment by aweell** [comment]
Closed via #498
