### ISSUE TITLE
In UX configuration, there is no option to change color of Link component

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#436]
**Describe the bug**
In UX configuration, there is no option to change color of Link component, like it is there for other components like header,footer,select box etc.

As per our requirement we want the link to be displayed as purple.

**To Reproduce**
Open platform console and in UX Configuration - there is no link component available for changing.

**Expected behavior**
Under WX Configuration, we should be having Link component.

Please let us know if any additional info required.

**Comment by ppurumala** [comment]
As discussed with BA Community, it became required again. Hence reopeing

**Comment by aweell** [comment]
Hi @ppurumala,

Since this request is not related to the Halstack design guidelines I close the issue. This should be discussed with the UX Configuration service maintainers.
