### ISSUE TITLE
[Input-text] Label `font-size` property regarding readability

### ISSUE THREAD

**Issue by aweell** [dxc-technology/halstack-style-guide#54]
Review the possibility increase of the label `font-size` when ` input-text` component is active

Font size (enabled) | 16px
-- | --
Font size (active] | 12px

Related issue (#53)

**Comment by sponnuswamydxc** [comment]
Atleast 14px should be better for font size (active)

**Comment by pwadhwani** [comment]
Hi @aweell @jsardid , Could you please provide updates on this ticket.

**Comment by aweell** [comment]
Hello @pwadhwani, 

The draft of the input component review is planned to be available at the end of release 3.2.0, as can be seen in **the milestone witch the issue is linked**. 

After the release of the draft, the component still needs to be implemented. The guidelines from [Developer Central](https://developer.dxc.com/design/components/text-input) and the CDKs will be released simultaneously when this steps are completed.

**Comment by pwadhwani** [comment]
@peibolsang @jsardid @aweell Could you please share ETC on this ticket.

**Comment by aweell** [comment]
[Draft of the input documentation]( https://github.com/dxc-technology/halstack-style-guide/blob/draft-3.2.0-text-input/guidelines/components/text-input/README.md) has been added to the `draft-3.2.0-text-input` branch.

* The label `font-size` has been increased to 14px
* The label `font-weight` has changed from regular to semi-bold
