### ISSUE TITLE
[progress-bar] Size not adaptable to fit table	

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-style-guide#76]
**Describe the bug**
CDK components are way too large to fit in
There is a class applied on this bar which provide min width of 685px.

**To Reproduce**

1. Create a new React App using `create-react-app`
2. Install the `@dxc-technology\halstack-react` dependencies and run the app
3. Create a table with column width=300px
4. Put the progressbar into a cell
5. The progress bar doesn't fit the cell, it takes 685px.

**Expected behavior**
The progress bar have to fit its parent container

**Screenshots**
![image](https://user-images.githubusercontent.com/62135994/115535825-66017680-a299-11eb-8275-3ccc864a6a86.png)

**Additional context**

**Add labels**
React HalStack V3

**Comment by aweell** [comment]
Hello @NorbertPointu,

Thanks for the feedback, since is a limitation in your case but also in terms of responsiveness, we need to review the `min/max-width` of the progress bar component.

**Comment by aweell** [comment]
Closed via 8f5577c521052aa060300df365ec338ee92b4067
