### ISSUE TITLE
Layout - Specs in Application Layout 

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#77]
In the Documentation Maximum width is set for the main area of **1320 pixels,**
but for desktop we use **width 1920 pixels** and

margins as Top 64px, Bottom 80px, Left /Right 15.6% and so on..

_What will be the Maximum Width?_

**Comment by aweell** [comment]
Thanks @mnnaveenk,

The value of `max-width` is set as 1320px to leave white space when screens from 1440+ are used. Values for `margin-left` and `margin-right` are set in percentage to accommodate and center horizontally this container in any desktop viewport size.
