### ISSUE TITLE
Default Dialog 

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#91]
The ‘X’ icon min size = 20x20px according to documentation in the example it is  34x34px

![image](https://user-images.githubusercontent.com/83015051/115746057-a2c09100-a3b1-11eb-82d1-54567519e54a.png)

Padding is 0 in the example

![image](https://user-images.githubusercontent.com/83015051/115746335-e2877880-a3b1-11eb-9146-cf1f1c8113f0.png)

Default Margin in the example is 48px all sides

**Comment by aweell** [comment]
This is already covered in #49
