### ISSUE TITLE
Dropdown - Specs Does not match with examples

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#94]
Margin is 15px in the table in the documentation but in the working example is 24px all sides

![image](https://user-images.githubusercontent.com/83015051/115747851-43fc1700-a3b3-11eb-9c44-e418a35fb2dc.png)

**Dropdown** (shown)

Padding is 0px 13px 0px 18px in the example
Even in the last option
Height is 48px and padding is 0px 16px is different in example

**Comment by aweell** [comment]
Already covered in #39. 

Action items:

- [ ] Specs images should be updated
