### ISSUE TITLE
[Tabbed Sections] Documentation update

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#99]
Different states with various styles and icons, tabs in different layouts are missing.
More example should be available as per documnetaion and UI Kit.

![Picture3](https://user-images.githubusercontent.com/75359999/115825379-f7eaba00-a426-11eb-8e09-5af907828038.png)

**Comment by GauravMaurya0** [comment]
**Usage**
Tabs organize and allow navigation between groups of content that are related and at the same level of hierarchy.

**Types**

**Formatting
Anatomy**
Container
Active icon (Optional if there’s a label)
Active text label (Optional if there’s an icon)
Active tab indicator
Inactive icon (Optional if there’s a label)
Inactive text label (Optional if there’s an icon)
Tab item
Divider

**Text label**
Text labels should clearly and succinctly describe the content of the tab they represent. Tab content should contain a cohesive set of items that share a common characteristic.

**Icons**
Icons communicate the type of content a tab represents in a simple, recognizable way. However, they aren’t as effective as text labels at communicating complex

**Active tab indicators**
To differentiate an active tab from an inactive tab, apply an underline and color change to the active tab’s text and icon.

**Behavior**

**Placement**
Tab layout
Fixed tabs
Scrollable tabs

**States**
By default, tabs inherit enabled states with one active state.
The inactive state of a tab can inherit a hover, focus, and pressed state.

**Comment by aweell** [comment]
Hello @GauravMaurya0,

We are discussing the possibility of adding more examples to the CDK sites. Until then since all variants are achievable by code, we consider there's not any design issue.
